// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVsD0GutFyxHQXcWeAcyNmDYvdSuPRMPo',
    appId: '1:937238551734:web:20bc114c01dbd786d6da17',
    messagingSenderId: '937238551734',
    projectId: 'jigue-aafbe',
    authDomain: 'jigue-aafbe.firebaseapp.com',
    storageBucket: 'jigue-aafbe.firebasestorage.app',
    measurementId: 'G-QCQ2JZ1WG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc3Vn6ANdX2Rko9eVhB8qt56RmsBldoyo',
    appId: '1:937238551734:android:4f01ed6b91e649dcd6da17',
    messagingSenderId: '937238551734',
    projectId: 'jigue-aafbe',
    storageBucket: 'jigue-aafbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh7rm-rr3MryC8xgbb_k89eub5szdLllg',
    appId: '1:937238551734:ios:3bd2557b04be0f56d6da17',
    messagingSenderId: '937238551734',
    projectId: 'jigue-aafbe',
    storageBucket: 'jigue-aafbe.firebasestorage.app',
    iosBundleId: 'com.example.ventou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh7rm-rr3MryC8xgbb_k89eub5szdLllg',
    appId: '1:937238551734:ios:3bd2557b04be0f56d6da17',
    messagingSenderId: '937238551734',
    projectId: 'jigue-aafbe',
    storageBucket: 'jigue-aafbe.firebasestorage.app',
    iosBundleId: 'com.example.ventou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVsD0GutFyxHQXcWeAcyNmDYvdSuPRMPo',
    appId: '1:937238551734:web:08ada93827fefba2d6da17',
    messagingSenderId: '937238551734',
    projectId: 'jigue-aafbe',
    authDomain: 'jigue-aafbe.firebaseapp.com',
    storageBucket: 'jigue-aafbe.firebasestorage.app',
    measurementId: 'G-T7C5PMLCWW',
  );
}
